name = "Default Config"
description = "Default configuration, containing all possible options"

[loading]
type = "load-all"

[loading.settings]

[segmentation]
type = "block"

[segmentation.settings]
block_length = 2000

[embedding]
type = "sentence-transformers"

[embedding.settings]
model = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

[sorting]
type = "similarity"

[sorting.settings]

[prompting]
type = "basic-prompt"

[prompting.settings]

[inference]
type = "unsloth"

[inference.settings]
model = "unsloth/Meta-Llama-3.1-8B"
max_tokens = 2048
